# Generated by Django 5.1.3 on 2024-11-20 21:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPIApp', '0002_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=uuid.UUID('3a7282c6-427a-4a9d-8cf5-3aaa8c6fb648'), max_length=36, unique=True),
        ),
    ]
