# Generated by Django 5.1.3 on 2024-11-20 21:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopAPIApp', '0003_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(default=uuid.UUID('d06eee59-b7e3-49c1-916a-63e38f0dd40c'), max_length=36, unique=True),
        ),
    ]
